In [1]:
from keras.models import Sequential
from ipynb.fs.full.DataGenerator import DataGenerator
from ipynb.fs.full.PreprocessData import Preprocessing

import os
import numpy as np
import matplotlib.pyplot as plt

import imgaug as ia
import imgaug.augmenters as iaa

In [2]:
class DataLoader:
    def __init__(self, samplesTrain, samplesVal, samplesTest, batch_size, augment_data, shuffle):
        self.samplesTrain = samplesTrain
        self.samplesVal = samplesVal
        self.samplesTest = samplesTest
        
        self.batch_size = batch_size
        self.augment_data = augment_data
        self.shuffle = shuffle
        
        self.train_data = None
        self.val_data = None
        self.test_data = None
        
        self.load_data()
    
    def load_data(self):
        preprocess_files = Preprocessing("input", self.samplesTrain, self.samplesVal, self.samplesTest)
        train_normal, train_pneumonia, test_normal, test_pneumonia, val_normal, val_pneumonia = preprocess_files.preprocess()
        
        self.train_data = self.load_train_data(train_normal, train_pneumonia)
        self.val_data = self.load_val_data(val_normal,val_pneumonia)
        self.test_data = self.load_test_data(test_normal, test_pneumonia)

    def load_train_data(self, train_normal, train_pneumonia):
        """
        retourne un tableau d'images en utilisant les train_normal et train_pneumonia dont les étiquettes sont respectivement
        0 et 1 lorsque NORMAL et PNEUMONIA concaténées
        np.shape(train_normal) ===> (224, 224, 3)
        np.shape(train_pneumonia) ===> (224, 224, 3)
        """
        X = np.concatenate((train_normal, train_pneumonia))
        y = np.concatenate((np.zeros(train_normal.shape[0]), np.ones(train_pneumonia.shape[0])))
        return (X, y)
    
    def load_val_data(self, val_normal, val_pneumonia):
        """
        retourne un tableau d'images val_normal et val_pneumonia dont les étiquettes sont NORMAL et PNEUMONIA concaténées
        """
        X = np.concatenate((val_normal, val_pneumonia))
        y = np.concatenate((np.zeros(val_normal.shape[0]), np.ones(val_pneumonia.shape[0])))
        return (X, y)
    
    def load_test_data(self, test_normal, test_pneumonia):
        """
        retourne un tableau d'images test_normal et test_pneumonia dont les étiquettes sont NORMAL et PNEUMONIA concaténées
        """
        X = np.concatenate((test_normal, test_pneumonia))
        y = np.concatenate((np.zeros(test_normal.shape[0]), np.ones(test_pneumonia.shape[0])))
        return (X, y)
    
    def load_train_generator(self):
        return DataGenerator(*self.train_data,
                             batch_size=self.batch_size,
                             shuffle=self.shuffle,
                             augment_data=self.augment_data
                            )

    def load_validation_generator(self):
        return DataGenerator(*self.val_data,
                             batch_size=self.batch_size,
                             shuffle=False,
                             augment_data=False
                            )
    
    def load_test_generator(self):
        print(self.test_data)
        return DataGenerator(*self.test_data,
                             batch_size=self.batch_size,
                             shuffle=False,
                             augment_data=False
                            )


In [3]:
# data_loader = DataLoader(samplesTrain= 5,
#                          samplesVal=10,
#                          samplesTest= 2,
#                          batch_size=64,
#                          augment_data=True,
#                          shuffle=True)

############################################################################################
input\train/NORMAL
Processed image 1/5
Processed image 2/5
Processed image 3/5
Processed image 4/5
############################################################################################
input\train/PNEUMONIA
Processed image 1/5
Processed image 2/5
Processed image 3/5
Processed image 4/5
############################################################################################
input\test/NORMAL
Processed image 1/2
Processed image 2/2
############################################################################################
input\test/PNEUMONIA
Processed image 1/2
Processed image 2/2
############################################################################################
input\val/NORMAL
Processed image 1/9
Processed image 2/9
Processed image 3/9
Processed image 4/9
Processed image 5/9
Processed image 6/9
Processed image 7/9
Processed image 8/9
######################################

In [4]:
# train_data = data_loader.load_train_generator()
# test_data  = data_loader.load_test_generator()
# val_data   = data_loader.load_validation_generator()

(array([[[[0.00283472, 0.00283472, 0.00283472],
         [0.00279951, 0.00279951, 0.00279951],
         [0.00282909, 0.00282909, 0.00282909],
         ...,
         [0.00261484, 0.00261484, 0.00261484],
         [0.0021895 , 0.0021895 , 0.0021895 ],
         [0.00274945, 0.00274945, 0.00274945]],

        [[0.00287839, 0.00287839, 0.00287839],
         [0.00291498, 0.00291498, 0.00291498],
         [0.00236017, 0.00236017, 0.00236017],
         ...,
         [0.00217162, 0.00217162, 0.00217162],
         [0.00269572, 0.00269572, 0.00269572],
         [0.00269863, 0.00269863, 0.00269863]],

        [[0.00288635, 0.00288635, 0.00288635],
         [0.0027989 , 0.0027989 , 0.0027989 ],
         [0.00300252, 0.00300252, 0.00300252],
         ...,
         [0.00258501, 0.00258501, 0.00258501],
         [0.0026419 , 0.0026419 , 0.0026419 ],
         [0.00246829, 0.00246829, 0.00246829]],

        ...,

        [[0.00249103, 0.00249103, 0.00249103],
         [0.00231115, 0.00231115, 0.00231115

In [10]:
# print(test_data[0][1])
# print(test_data[1][1])

images :  8
[0. 0. 1. 1. 0. 0. 1. 1.]
images :  0
[]


In [6]:
# train_X, train_y = train_data[0]
# test_X, test_y = test_data[0]
# val_X, val_y = val_data[0]

images :  16
images :  8
images :  32


In [7]:
# print(train_data[0][1], '\n', train_y)

images :  16
[1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1.] 
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1.]


In [8]:
# print(val_data[0][1], '\n', val_y)

images :  32
[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 1. 1. 1. 1.] 
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
# print(test_data[0][1], '\n', test_y)

images :  8
[0. 0. 1. 1. 0. 0. 1. 1.] 
 [0. 0. 1. 1. 0. 0. 1. 1.]
